name: Setup
description: Setup Xcode and Ruby
runs:
  using: 'composite'
  steps:
    - uses: actions/cache@v3
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    - name: Select Xcode version
      run: sudo xcode-select -s '/Applications/Xcode_13.3.1.app/Contents/Developer'
      shell: bash
    - name: Show Xcode version
      run: xcodebuild -version
      shell: bash
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true