# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Runs generate config"
  lane :config do
    Dir.chdir("../scripts") do
      sh("./config.sh")
    end
  end

  desc "Runs format"
  lane :format do
    Dir.chdir("../scripts") do
      sh("./swift-format.sh", "-f")
    end
  end

  desc "Runs lint"
  lane :lint do
    Dir.chdir("../scripts") do
      sh("./swift-format.sh", "-l")
    end
  end

  desc "Runs Test"
  lane :test do
    scan(
      package_path: "./TemplateView",
      scheme: "TemplateView",
      derived_data_path: ENV["DERIVED_DATA_PATH"],
      devices: ["iPhone 8"],
      output_directory: "fastlane/test_output/TemplateView",
      skip_build: true
    )
  end
end
