name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    env:
      BUNDLE_ID: dev.yhiguchi.Template
      DERIVED_DATA_PATH: ~/Library/Developer/Xcode/DerivedData
    steps:
      - uses: actions/checkout@v3
      - name: Setup Xcode and Ruby
        uses: ./.github/actions/setup
      - name: Set env
        run: |
          echo "BUNDLE_VERSION=0.1.0" >> "${GITHUB_ENV}"
          echo "BUILD_DATE=$(date "+%Y-%m-%d-%H-%M")" >> "${GITHUB_ENV}"
      - name: Generate env
        run: bundle exec fastlane generate_env
      - name: Run lint
        run: bundle exec fastlane lint
      - name: Run Test
        run: bundle exec fastlane test
      - uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: TestReports/