name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Super-Linter
        uses: github/super-linter@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          FILTER_REGEX_EXCLUDE: .*.swift
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: .build
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-
      - name: Lint
        run: swift run swift-format lint -r ./Package.swift -r ./Template/ -r ./TemplateView
      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_13.2.1.app/Contents/Developer'
      - name: Show Xcode version
        run: xcodebuild -version